### ISSUE TITLE
关于pipe

### ISSUE THREAD

**Issue by jiajianrong** [liyangready/mini-proxy#2]
https://github.com/liyangready/mini-proxy/blob/master/lib/MiniProxy.js 中的`requestRemote`方法为啥要两个response互相pipe呢？我理解有前面那行就足够了啊

```
// u can change resonse here
proxy.emit("beforeResponse", remoteResponse);
remoteResponse.pipe(res);
// Res could not write, but it could close connection
res.pipe(remoteResponse);
```

**Comment by hk20181001** [comment]
res.pipe(remoteResponse); 崩溃了
proxy start at 9000
proxy request :www.163.com/
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error [ERR_STREAM_CANNOT_PIPE]: Cannot pipe, not readable
    at ServerResponse.pipe (_http_outgoing.js:821:22)
    at ClientRequest.<anonymous> (/root/node_modules/mini-proxy/lib/MiniProxy.js:70:17)
    at Object.onceWrapper (events.js:277:13)
    at ClientRequest.emit (events.js:189:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:556:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
    at Socket.socketOnData (_http_client.js:442:20)
    at Socket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
Emitted 'error' event at:
    at ServerResponse.onerror (_stream_readable.js:713:12)
    at ServerResponse.emit (events.js:189:13)
    at ServerResponse.pipe (_http_outgoing.js:821:8)
    at ClientRequest.<anonymous> (/root/node_modules/mini-proxy/lib/MiniProxy.js:70:17)
    [... lines matching original stack trace ...]
    at Socket.emit (events.js:189:13)

**Comment by liyangready** [comment]
这个地方可能的确有点多余

**Comment by liyangready** [comment]
fix : https://github.com/liyangready/mini-proxy/blob/master/lib/MiniProxy.js#L72
